#!/usr/bin/env python3
"""Generates every MusicStream icon from one glyph definition.

The glyph (three equalizer bars, the last one ending in a wave) is drawn in
the 108-unit adaptive icon viewport. Android gets vector drawables; legacy
Android, iOS and store assets get PNGs rasterized here with Pillow.

Run from the repository root: python3 scripts/generate_branding.py
"""

from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "android/app/src/main/res"
IOS_ICONS = ROOT / "ios/Runner/Assets.xcassets/AppIcon.appiconset"
IOS_LAUNCH = ROOT / "ios/Runner/Assets.xcassets/LaunchImage.imageset"
BRANDING = ROOT / "assets/branding"

VIOLET = (0x7C, 0x4D, 0xFF)
PINK = (0xE4, 0x3F, 0x83)
STROKE = 9.0
# Straight bars share one baseline; the last bar curves into a wave.
BARS = [((33, 56), (33, 70)), ((47, 36), (47, 70))]
WAVE_LINE = ((61, 46), (61, 63))
WAVE_CURVE = ((61, 63), (61, 72), (71, 73), (77, 56))
WAVE_PATH = "M61,46 L61,63 C61,72 71,73 77,56"


def _hex(color):
    return "#FF%02X%02X%02X" % color


def _bezier(p0, p1, p2, p3, steps=80):
    for i in range(steps + 1):
        t = i / steps
        u = 1 - t
        yield (
            u**3 * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t**3 * p3[0],
            u**3 * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t**3 * p3[1],
        )


def glyph_mask(size, scale=1.0, offset=(0.0, 0.0)):
    """White-on-black glyph mask; [scale] and [offset] are in 108 units."""
    ss = 4  # Supersampling for smooth round caps.
    big = size * ss
    unit = big / 108 * scale
    mask = Image.new("L", (big, big), 0)
    draw = ImageDraw.Draw(mask)
    radius = STROKE / 2 * unit

    def point(p):
        cx = (p[0] - 54) * unit + big / 2 + offset[0] * big / 108
        cy = (p[1] - 54) * unit + big / 2 + offset[1] * big / 108
        return cx, cy

    def dot(p):
        x, y = point(p)
        draw.ellipse((x - radius, y - radius, x + radius, y + radius), fill=255)

    for start, end in BARS + [WAVE_LINE]:
        draw.line([point(start), point(end)], fill=255, width=round(radius * 2))
        dot(start)
        dot(end)
    for p in _bezier(*WAVE_CURVE):
        dot(p)
    return mask.resize((size, size), Image.LANCZOS)


def gradient(size):
    """Diagonal violet-to-pink gradient, top-left to bottom-right."""
    small = Image.new("RGB", (256, 256))
    pixels = small.load()
    for y in range(256):
        for x in range(256):
            t = (x + y) / 510
            pixels[x, y] = tuple(round(a + (b - a) * t) for a, b in zip(VIOLET, PINK))
    return small.resize((size, size), Image.BICUBIC)


def rounded_mask(size, radius_ratio):
    ss = 4
    mask = Image.new("L", (size * ss, size * ss), 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        (0, 0, size * ss - 1, size * ss - 1), radius=size * ss * radius_ratio, fill=255
    )
    return mask.resize((size, size), Image.LANCZOS)


def app_icon(size, corner=None, glyph_scale=1.45):
    """Gradient tile with the white glyph; [corner] rounds it (None: square)."""
    icon = gradient(size).convert("RGBA")
    white = Image.new("RGBA", (size, size), (255, 255, 255, 255))
    icon.paste(white, (0, 0), glyph_mask(size, glyph_scale))
    if corner is not None:
        icon.putalpha(rounded_mask(size, corner))
    return icon


def launch_image(size):
    """Glyph inside a gradient circle on a transparent canvas."""
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    ss = 4
    circle = Image.new("L", (size * ss, size * ss), 0)
    ImageDraw.Draw(circle).ellipse((0, 0, size * ss - 1, size * ss - 1), fill=255)
    canvas.paste(gradient(size), (0, 0), circle.resize((size, size), Image.LANCZOS))
    white = Image.new("RGBA", (size, size), (255, 255, 255, 255))
    canvas.paste(white, (0, 0), glyph_mask(size, 1.25))
    return canvas


def vector(path_data, color, viewport=108, size=108, extra=""):
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_branding.py; edit the script instead. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp"
    android:height="{size}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}">
{extra}{path_data(color)}</vector>
"""


def glyph_paths(color, transform=""):
    lines = [f"M{a[0]},{a[1]} L{b[0]},{b[1]}" for a, b in BARS] + [WAVE_PATH]
    body = "".join(
        f"""        <path
            android:pathData="{d}"
            android:strokeColor="{color}"
            android:strokeWidth="{STROKE}"
            android:strokeLineCap="round"
            android:strokeLineJoin="round" />
"""
        for d in lines
    )
    return f"""    <group{transform}>
{body}    </group>
"""


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def android():
    # The adaptive foreground scales the glyph around the centre so it fills
    # the 66-unit safe zone like the reference sheet.
    scaled = (
        ' android:pivotX="54" android:pivotY="54"'
        ' android:scaleX="1.12" android:scaleY="1.12"'
    )
    write(
        RES / "drawable/ic_launcher_foreground.xml",
        vector(lambda c: glyph_paths(c, scaled), "#FFFFFFFF"),
    )
    write(
        RES / "drawable/ic_launcher_monochrome.xml",
        vector(lambda c: glyph_paths(c, scaled), "#FFFFFFFF"),
    )
    gradient_bg = f"""    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="0"
                android:startY="0"
                android:endX="108"
                android:endY="108"
                android:startColor="{_hex(VIOLET)}"
                android:endColor="{_hex(PINK)}" />
        </aapt:attr>
    </path>
"""
    write(
        RES / "drawable/ic_launcher_background.xml",
        vector(lambda _: gradient_bg, None).replace(
            'xmlns:android="http://schemas.android.com/apk/res/android"',
            'xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    xmlns:aapt="http://schemas.android.com/aapt"',
        ),
    )
    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_branding.py; edit the script instead. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""
    write(RES / "mipmap-anydpi-v26/ic_launcher.xml", adaptive)
    # Status bar icon: white glyph only, cropped around it in a 24dp icon.
    write(
        RES / "drawable/ic_stat_musicstream.xml",
        vector(
            lambda c: glyph_paths(
                c,
                ' android:translateX="-24" android:translateY="-24"'
                ' android:scaleX="1" android:scaleY="1"',
            ),
            "#FFFFFFFF",
            viewport=60,
            size=24,
        ),
    )
    # Splash logo for Android 11 and older: glyph in a gradient circle.
    circle = f"""    <path android:pathData="M54,0a54,54 0,1 1,0 108a54,54 0,1 1,0 -108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="0"
                android:startY="0"
                android:endX="108"
                android:endY="108"
                android:startColor="{_hex(VIOLET)}"
                android:endColor="{_hex(PINK)}" />
        </aapt:attr>
    </path>
"""
    logo_glyph = glyph_paths(
        "#FFFFFFFF",
        ' android:pivotX="54" android:pivotY="54"'
        ' android:scaleX="1.25" android:scaleY="1.25"',
    )
    write(
        RES / "drawable/ic_launch_logo.xml",
        vector(lambda _: circle + logo_glyph, None).replace(
            'xmlns:android="http://schemas.android.com/apk/res/android"',
            'xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    xmlns:aapt="http://schemas.android.com/aapt"',
        ),
    )
    # Legacy launchers (API 23-25) use rounded PNG tiles.
    for folder, size in {
        "mdpi": 48,
        "hdpi": 72,
        "xhdpi": 96,
        "xxhdpi": 144,
        "xxxhdpi": 192,
    }.items():
        out = RES / f"mipmap-{folder}/ic_launcher.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        app_icon(size, corner=0.22).save(out, optimize=True)


def ios():
    for name in sorted(p.name for p in IOS_ICONS.glob("Icon-App-*.png")):
        spec = name[len("Icon-App-") : -len(".png")]
        points, scale = spec.split("@")
        size = round(float(points.split("x")[0]) * int(scale.rstrip("x")))
        # App Store icons must be opaque and square; iOS applies the mask.
        app_icon(size).convert("RGB").save(IOS_ICONS / name, optimize=True)
    for suffix, size in {"": 168, "@2x": 336, "@3x": 504}.items():
        launch_image(size).save(IOS_LAUNCH / f"LaunchImage{suffix}.png", optimize=True)


def store():
    BRANDING.mkdir(parents=True, exist_ok=True)
    app_icon(512).convert("RGB").save(BRANDING / "store_icon_512.png", optimize=True)
    app_icon(1024).convert("RGB").save(BRANDING / "app_icon_1024.png", optimize=True)


if __name__ == "__main__":
    android()
    ios()
    store()
    print("Branding assets generated.")
